name: Android CI

on:
  push:
    branches:
    - master
    - setup/*
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
      SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
      SIGNING_STORE_FILE: ${{ secrets.SIGNING_STORE_FILE }}
      SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Secrets
      run: echo "signing.key.alias=$SIGNING_KEY_ALIAS" >> local.properties
      run: echo "signing.key.password=$SIGNING_KEY_PASSWORD" >> local.properties
      run: echo "signing.store.file=$SIGNING_STORE_FILE" >> local.properties
      run: echo "signing.store.password=$SIGNING_STORE_PASSWORD" >> local.properties
    - name: Detekt
      run: ./gradlew detekt
