name: Internal Release

on:
  push:
    branches:
      - release/**
  pull_request:
    branches:
      - release/**

jobs:
  release:
    name: Validate and release
    runs-on: ubuntu-latest
    env:
      SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
      SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
      SIGNING_STORE_FILE: ${{ secrets.SIGNING_STORE_FILE }}
      SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      KEYSTORE: ${{ secrets.KEYSTORE }}
      VERSION_CODE: ${{ secrets.VERSION_CODE }}
    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
        run: echo running on branch ${GITHUB_REF##*/}
      - name: Add secrets
        run: |
          echo "signing.key.alias=$SIGNING_KEY_ALIAS" >> local.properties
          echo "signing.key.password=$SIGNING_KEY_PASSWORD" >> local.properties
          echo "signing.store.file=$SIGNING_STORE_FILE" >> local.properties
          echo "signing.store.password=$SIGNING_STORE_PASSWORD" >> local.properties
          echo $GOOGLE_SERVICES_JSON | base64 -di > app/google-services.json
          echo $KEYSTORE | base64 -di > app/keystore.jks
      - name: Unit tests
        run: bash ./gradlew testDevDebugUnitTest
      - name: Update release version
        run: |
          latest_release="${GITHUB_REF##*/}"
          version_name="\"$latest_release\""
          sed -i "s/BuildAndroidConfig.VERSION_NAME/$version_name/g" app/build.gradle.kts
          sed -i "s/BuildAndroidConfig.VERSION_CODE/$VERSION_CODE/g" app/build.gradle.kts
      - name: Build Signed Bundle
        run: bash ./gradlew :app:bundleProdRelease
      - name: Upload Bundle artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release
          path: app/build/outputs/bundle/prodRelease/app-prod-release.aab

  uploadBundle:
    name: Upload Bundle to Google Play
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/checkout@v2
      - name: Download app Bundle
        uses: actions/download-artifact@v1
        with:
          name: app-release
      - name: Upload Android Release to Play Store
        uses: r0adkll/upload-google-play@v1.0.4
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT }}
          packageName: com.jpaya.englishisfun
          releaseFile: app-release/app-prod-release.aab
          track: internal
          whatsNewDirectory: whatsnew
